---
title: ''
output: word_document
---

```{r include=FALSE, message = FALSE, error = FALSE, warning = FALSE}

# 1 packages ----
library(tidyverse)
library(purrr)
library(lubridate)
library(readxl)
library(flextable)
library(officer)

source("C:/Users/scott.jennings/Documents/Projects/R_general/utility_functions/bird_utility_functions.R")
source("C:/Users/scott.jennings/Documents/Projects/R_general/utility_functions/analysis_utility_functions.R")
source("C:/Users/scott.jennings/Documents/Projects/R_general/utility_functions/numbers2words.r")

options(scipen = 999)


```


```{r include=FALSE, message = FALSE, error = FALSE, warning = FALSE}
#wbirds_start <- read.csv("C:/Users/scott.jennings/Documents/Projects/water_birds/data_files/qsel_all_data.csv")
#names(wbirds_start)<- tolower(names(wbirds_start))
wbirds_start <- readRDS("C:/Users/scott.jennings/Documents/Projects/water_birds/data_files/working_rds/wbirds4analysis")
wbirds <- wbirds_start %>% 
  filter(section.final > 0) %>% 
  distinct(., alpha.code) %>% 
  rename(species = alpha.code) %>% 
  fix_4letter_codes() %>% 
  bird_taxa_filter() %>% 
  arrange(species.number)

out_table <- wbirds %>% 
  select(common.name, species)


```



```{r echo = FALSE, message = FALSE, error = FALSE, warning = FALSE}

flextable(out_table) %>%   
  set_header_labels(common.name = "Common name") %>%
  set_header_labels(species = "Species") %>%
  border_remove() %>% 
  border(i = 1, border.top = fp_border(color = "black"), part = "header") %>% 
  border(i = 1, border.top = fp_border(color = "black"), part = "body") %>% 
  border(i = nrow(out_table), border.bottom = fp_border(color = "black"), part = "body") %>% 
  align_nottext_col(align = "center") %>% 
  align_text_col(align = "left")  %>%
  autofit() %>% 
  fit_to_width(max_width = 7.5) %>% 
  italic(., j = 2, italic = TRUE, part = "body") 

```


